import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Lock, Sparkles, Calculator, ChevronDown, CheckCircle2, Paperclip } from 'lucide-react'
import { useStore } from '@/lib/store'
import { FileTile } from '@/ds/composite'
import { Section, Field, Input, Select, Button, Callout, Badge, Code, KV, Tabs, cx } from '@/ds/primitives'

const LABELS: Record<string, string> = { bearing: 'قدرة تحمل التربة الصافية', settlement: 'الهبوط المتوقع', ks: 'معامل رد فعل التربة', lateral: 'Ka / Kp / K0 — معاملات الضغط الجانبي' }

export default function Analysis() {
  const { id } = useParams()
  const nav = useNavigate()
  const user = useStore(s => s.user)!
  const r = useStore(s => s.requests.find(x => x.id === id))!
  const st = useStore(s => s.studies.find(x => x.requestId === id))!
  const patch = useStore(s => s.patchStudy)
  const [step, setStep] = useState<'computed' | 'analytical' | 'recs'>('computed')
  const [openF, setOpenF] = useState<string | null>('bearing')
  const isL = user.role === 'lab'; const a = st.analysis; const readOnly = !isL || !!a.done
  const compute = (key: string) => patch(st.id, s => { const f = s.analysis.computed[key]; const phi = +(f.inputs['زاوية الاحتكاك φ'] || 30); if (key === 'bearing') f.value = String(Math.round((0.05 * 30 * 1.3 + 1.82 * 3 * (18.4 - 1) + 0.5 * 1.82 * +(f.inputs['عرض القاعدة B'] || 2) * 22.4 * 0.8) * 9.81 / +(f.inputs['عامل الأمان FS'] || 3))); if (key === 'settlement') f.value = String(Math.max(8, Math.round(+(f.inputs['الحمل الإنشائي'] || 150) * 3 / +(f.inputs['معامل الانضغاط'] || 25)))); if (key === 'ks') f.value = String(Math.round(185 / 0.025)); if (key === 'lateral') f.value = `${(Math.tan((45 - phi / 2) * Math.PI / 180) ** 2).toFixed(2)} / ${(Math.tan((45 + phi / 2) * Math.PI / 180) ** 2).toFixed(2)} / ${(1 - Math.sin(phi * Math.PI / 180)).toFixed(2)}` })
  const runAnalytical = () => patch(st.id, s => { const ns = s.boreholes.flatMap(b => b.layers.filter(l => l.n != null).map(l => l.n!)); const nbar = ns.length ? Math.round(ns.reduce((x, y) => x + y, 0) / ns.length) : 15; const cls = nbar > 50 ? 'C' : nbar >= 15 ? 'D' : 'E'; s.analysis.analytical = { 'التصنيف الزلزالي للتربة (Site Class)': cls, 'N̄ (متوسط SPT في أعلى 30 م)': String(nbar), 'Ss': '0.85 g', 'S1': '0.32 g', 'Fa': cls === 'D' ? '1.2' : cls === 'C' ? '1.0' : '1.4', 'Fv': cls === 'D' ? '1.8' : cls === 'C' ? '1.5' : '2.4', 'Vs30 (مقدّر)': `${cls === 'D' ? 210 : cls === 'C' ? 380 : 160} m/s`, 'PGA': '0.24 g', 'التكوين الجيولوجي': 'رواسب رملية طينية', 'المرجع': 'SBC 301-2018 — الفصل 20 (تصنيف الموقع من N̄)، الفصل 22 (خرائط Ss/S1/PGA)، §11.4 (Fa/Fv)' } })
  const runRecs = () => patch(st.id, s => { const q = +(s.analysis.computed.bearing.value ?? 185); const w = s.boreholes[0]?.head?.water24h ?? 8; s.analysis.recommendations = { 'نوع الأساس الموصى به': q >= 150 ? 'لبشة خرسانية' : 'قواعد منفصلة', 'عمق التأسيس الموصى به': `${(s.prelim.foundationDepth ?? 3) + 0.5} م`, 'قدرة التحمل المسموح بها': `${q} kN/m²`, 'الهبوط المسموح به': '25 mm', 'نوع الأسمنت': s.chemical?.results.find(t => t.id === 'ch-so4')?.value && +s.chemical.results.find(t => t.id === 'ch-so4')!.value! > 0.2 ? 'Type V (مقاوم للكبريتات)' : 'Type II', 'نوع حديد التسليح': 'عادي', 'توصيات المياه الجوفية': w < (s.prelim.foundationDepth ?? 3) + 2 ? 'عزل مائي إلزامي + نظام تصريف' : 'عزل مائي إلزامي', 'توصيات الصرف السطحي': 'نظام صرف دائم', 'الحد الأدنى للمحتوى الأسمنتي': '350 kg/m³', 'الحد الأدنى للغطاء الخرساني': '75 mm (SBC 304)', 'المرجع': 'قاعدة المعرفة v1.2 — SBC 303 الفصل 4 (Presumptive Load-Bearing Values)، SBC 304 (حماية الخرسانة)' } })
  const computedDone = Object.values(a.computed).every(f => f.value)
  return (
    <div className="card">
      <Tabs value={step} onChange={setStep} className="px-3 pt-1" items={[{ value: 'computed', label: '1 · الحقول الحسابية', count: Object.values(a.computed).filter(f => f.value).length }, { value: 'analytical', label: '2 · الحقول التحليلية (المحرك الذكي)' }, { value: 'recs', label: '3 · التوصيات' }]} />
      <div className="grid grid-cols-12 gap-3 p-3">
        <div className="col-span-12 grid content-start gap-3 xl:col-span-8">
          {step === 'computed' && <><Callout tone="info" compact>افتح كل حقل لإدخال مدخلاته — تُحسب النتيجة تلقائياً بالمعادلة المعرّفة (v1.2) فور اكتمال المدخلات وتُعاد عند تعديل أي مدخل قبل إصدار التقرير (B.R.212–214). الحقول محمية من التعديل اليدوي (B.R.218).</Callout>
            {Object.entries(a.computed).map(([k, f]) => <div key={k} className="rounded-md border border-ink-200"><button type="button" onClick={() => setOpenF(openF === k ? null : k)} className="flex w-full items-center justify-between px-3 py-2.5 text-start"><div className="flex items-center gap-2"><Calculator className="size-4 text-ink-500" /><span className="text-[13px] font-bold">{LABELS[k]}</span></div><div className="flex items-center gap-2">{f.value ? <span className="num text-[16px] font-bold text-brand-700">{f.value} <span className="meta">{f.unit}</span></span> : <Badge tone="warn" size="xs">بانتظار المدخلات</Badge>}<Lock className="size-3.5 text-ink-400" /><ChevronDown className={cx('size-4 text-ink-400 transition-transform', openF === k && 'rotate-180')} /></div></button>{openF === k && <div className="border-t border-ink-100 px-3 py-3"><div className="mb-2 rounded-sm bg-ink-50 px-2.5 py-1.5 font-mono text-[11.5px] text-ink-700" dir="ltr">{f.formula}</div><div className="grid gap-2 sm:grid-cols-3">{Object.entries(f.inputs).map(([ik, iv]) => <Field key={ik} label={ik}><Input value={iv} onChange={e => { patch(st.id, s => { s.analysis.computed[k].inputs[ik] = e.target.value; s.analysis.computed[k].value = undefined }); const next = { ...f.inputs, [ik]: e.target.value }; if (Object.values(next).every(v => v)) compute(k) }} className="ltr h-8" disabled={readOnly} /></Field>)}</div>{!readOnly && <Button size="xs" variant="secondary" icon={Calculator} className="mt-2" disabled={Object.values(f.inputs).some(v => !v)} onClick={() => compute(k)}>احسب</Button>}</div>}</div>)}
            <div className="flex justify-end"><Button disabled={!computedDone} onClick={() => setStep('analytical')}>التالي: الحقول التحليلية</Button></div></>}
          {step === 'analytical' && <><Callout tone="info" compact><Sparkles className="me-1 inline size-3.5" />الحقول التحليلية نواتج المحرك الذكي (قاعدة المعرفة + SBC 301) — غير قابلة للتعديل. تصنيف الموقع يُشتق من قيم SPT المسجّلة في الجسات.</Callout>
            {Object.keys(a.analytical).length === 0 ? <div className="rounded-md border border-dashed border-ink-300 p-6 text-center"><Sparkles className="mx-auto mb-1 size-7 text-brand-600" /><p className="text-[12.5px] text-ink-600">لم تُنتج الحقول التحليلية بعد.</p>{!readOnly && <Button className="mt-3" icon={Sparkles} onClick={runAnalytical}>تشغيل المحرك الذكي</Button>}</div> : <Section title="الحقول التحليلية" icon={Lock} bodyClass="p-3"><KV cols={4} dense items={Object.entries(a.analytical).filter(([k]) => k !== 'المرجع').map(([k, v]) => ({ k, v }))} /><div className="mt-3 rounded-sm bg-brand-50 px-2.5 py-1.5 text-[11.5px] text-brand-800"><b>المرجع:</b> {a.analytical['المرجع']}</div></Section>}
            <Section title="رسومات ومرفقات (اختياري)" icon={Paperclip} bodyClass="p-3"><FileTile onChange={readOnly ? undefined : () => patch(st.id, s => { s.analysis.attachments.push(`مخطط-التصنيف-الزلزالي-${s.analysis.attachments.length + 1}.png`) })} hint="PNG / PDF" />{a.attachments.length > 0 && <ul className="mt-2 grid gap-1 text-[12px]">{a.attachments.map(f => <li key={f} className="flex items-center gap-1.5 text-brand-700"><Paperclip className="size-3.5" />{f}</li>)}</ul>}</Section>
            <div className="flex justify-between"><Button variant="ghost" onClick={() => setStep('computed')}>السابق</Button><Button disabled={!Object.keys(a.analytical).length} onClick={() => setStep('recs')}>التالي: التوصيات</Button></div></>}
          {step === 'recs' && <>{Object.keys(a.recommendations).length === 0 ? <div className="rounded-md border border-dashed border-ink-300 p-6 text-center"><Sparkles className="mx-auto mb-1 size-7 text-brand-600" /><p className="text-[12.5px] text-ink-600">التوصيات تُنتج من قاعدة المعرفة اعتماداً على البيانات المعتمدة والحقول الحسابية والتحليلية.</p>{!readOnly && <Button className="mt-3" icon={Sparkles} onClick={runRecs}>إنتاج التوصيات</Button>}</div> : <Section title="حقول التوصيات" icon={Lock} bodyClass="p-3"><KV cols={3} dense items={Object.entries(a.recommendations).filter(([k]) => k !== 'المرجع').map(([k, v]) => ({ k, v }))} /><div className="mt-3 rounded-sm bg-brand-50 px-2.5 py-1.5 text-[11.5px] text-brand-800"><b>المرجع:</b> {a.recommendations['المرجع']}</div></Section>}
            <Section title="مدخلات يدوية مسموحة" desc="حقول تتطلب إدخالاً بطبيعتها (B.R.219)" bodyClass="p-3"><div className="grid gap-3 sm:grid-cols-3"><Field label="وجود تكهفات"><Select value={a.manual['تكهفات'] ?? 'غير موجودة'} onChange={e => patch(st.id, s => { s.analysis.manual['تكهفات'] = e.target.value })} disabled={readOnly}><option>غير موجودة</option><option>موجودة</option></Select></Field><Field label="الميل الرأسي للحفر"><Input value={a.manual['الميل'] ?? '1:1'} onChange={e => patch(st.id, s => { s.analysis.manual['الميل'] = e.target.value })} className="ltr" disabled={readOnly} /></Field><Field label="صلاحية مواد الحفر للردم"><Select value={a.manual['الردم'] ?? 'صالحة جزئياً'} onChange={e => patch(st.id, s => { s.analysis.manual['الردم'] = e.target.value })} disabled={readOnly}><option>صالحة</option><option>صالحة جزئياً</option><option>غير صالحة</option></Select></Field></div></Section>
            <div className="flex justify-between"><Button variant="ghost" onClick={() => setStep('analytical')}>السابق</Button>{!readOnly && <Button icon={CheckCircle2} disabled={!Object.keys(a.recommendations).length} onClick={() => { patch(st.id, s => { s.analysis.done = true; s.phase = 6 }); nav(`/requests/${r.id}/study/6`) }}>مراجعة الحقول وتأكيد الاكتمال</Button>}</div>{a.done && <Callout tone="ok" compact>اكتمل التحليل الهندسي — تولّدت معاينة التقرير.</Callout>}</>}
        </div>
        <div className="col-span-12 grid content-start gap-3 xl:col-span-4">
          <Section title="مصادر البيانات المعتمدة" bodyClass="p-3"><KV cols={1} dense items={[{ k: 'الجسات المكتملة', v: `${st.boreholes.filter(b => b.status === 'done').length} / ${st.boreholes.length}` }, { k: 'متوسط N (SPT)', v: (() => { const ns = st.boreholes.flatMap(b => b.layers.filter(l => l.n != null).map(l => l.n!)); return ns.length ? Math.round(ns.reduce((x, y) => x + y, 0) / ns.length) : '—' })() }, { k: 'منسوب المياه', v: `${st.boreholes[0]?.head?.water24h ?? '—'} م` }, { k: 'عمق التأسيس', v: `${st.prelim.foundationDepth} م` }, { k: 'الكيميائية', v: st.chemical?.done ? 'معتمدة' : 'غير مكتملة' }, { k: 'إصدار المعادلات', v: <Code>v1.2</Code> }]} /></Section>
          <Callout tone="info" compact>إصدار المعادلات وقاعدة المعرفة مُثبَّت لهذه الدراسة ولا يتغير بعد إصدار التقرير (B.R.213). كل حقل يحمل مدخلاته ومعادلته للتتبع.</Callout>
        </div>
      </div>
    </div>
  )
}
