import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { MapPin, Camera, Plus, Save, CheckCircle2, Printer, Download, AlertTriangle } from 'lucide-react'
import { useStore } from '@/lib/store'
import { PageHeader } from '@/ds/composite'
import { GeoMap, PhotoGrid } from '@/ds/evidence'
import { photosFor } from '@/lib/evidence'
import { Section, Field, Input, Select, Textarea, Button, ButtonLink, Callout, Badge, Modal, Table, Th, Td, Code, Kpi, Progress, cx } from '@/ds/primitives'
import { BOREHOLE_STATUS } from '@/lib/statuses'
import type { USCS, Layer, Sample } from '@/lib/types'
import { fmtDate, uid } from '@/lib/format'

const USCS_LIST: { v: USCS; l: string }[] = [{ v: 'SM', l: 'SM — رمل طمي' }, { v: 'SC', l: 'SC — رمل طيني' }, { v: 'SW', l: 'SW — رمل جيد التدرج' }, { v: 'SP', l: 'SP — رمل ضعيف التدرج' }, { v: 'ML', l: 'ML — طمي منخفض اللدونة' }, { v: 'CL', l: 'CL — طين منخفض اللدونة' }, { v: 'CH', l: 'CH — طين عالي اللدونة' }, { v: 'GW', l: 'GW — حصى جيد التدرج' }, { v: 'GP', l: 'GP — حصى ضعيف التدرج' }, { v: 'ROCK', l: 'ROCK — صخر' }]
const nDesc = (n: number) => n < 4 ? 'مفككة جداً' : n < 10 ? 'مفككة' : n < 30 ? 'متوسطة الكثافة' : n < 50 ? 'كثيفة' : 'كثيفة جداً'
export const USCS_COLOR: Record<string, string> = { SM: '#E8DFA8', SC: '#D9C27A', SW: '#EFE6B5', SP: '#F2EBC4', ML: '#CFCBB8', CL: '#B9B39A', CH: '#9E987F', GW: '#C9C2A0', GP: '#D5CFAF', ROCK: '#A89F8C' }

export default function Borehole() {
  const { id, bhId } = useParams()
  const nav = useNavigate()
  const user = useStore(s => s.user)!
  const r = useStore(s => s.requests.find(x => x.id === id))!
  const st = useStore(s => s.studies.find(x => x.requestId === id))!
  const patch = useStore(s => s.patchStudy)
  const rules = useStore(s => s.rules)
  const b = st.boreholes.find(x => x.id === bhId)
  const [head, setHead] = useState(b?.head ?? { method: 'حفر دوراني رطب (Rotary Wash)', rig: 'CME-75', diameter: 100, casing: 3, groundLevel: 4.85, waterInstant: undefined, water24h: undefined, technician: user.name, weather: 'صافٍ' })
  const [offsite, setOffsite] = useState(false)
  const [offReason, setOffReason] = useState('')
  const lastTo = b?.layers.at(-1)?.to ?? 0
  const [L, setL] = useState<Partial<Layer> & { spt?: [number, number, number] }>({ from: lastTo, uscs: 'SM', gradation: 'ناعم إلى متوسط', color: 'بني فاتح', moisture: 'رطبة قليلاً' })
  const [samples, setSamples] = useState<{ type: Sample['type'] }[]>([{ type: 'SPT' }])
  const [complete, setComplete] = useState(false)
  const [notReached, setNotReached] = useState('')
  const isL = user.role === 'lab' && useStore.getState().can('study.field')
  const delegate = useStore.getState().users.find(u => u.id === r.tests[0]?.delegateId)?.name
  if (!b) return <Callout tone="danger">الجسة غير موجودة.</Callout>
  const n = L.spt ? L.spt[1] + L.spt[2] : undefined
  const reached = (b.executedDepth ?? 0) >= b.approvedDepth
  const canAdd = L.to != null && L.to > (L.from ?? 0) && L.uscs && (!offsite || offReason.trim().length > 5)
  const readOnly = b.status === 'done' || !isL
  const bhNo = b.code.replace('BH-', '').replace(/^0/, '')

  const start = () => patch(st.id, s => { const x = s.boreholes.find(y => y.id === b.id)!; x.status = 'in-progress'; x.actual = { n: +((x.operational ?? x.approved).n + 0.00001).toFixed(5), e: +((x.operational ?? x.approved).e + 0.00001).toFixed(5) }; x.geoVerified = { distance: 1.2 }; x.head = { ...head, date: new Date().toISOString() } as any; x.executedDepth = 0 })
  const saveHead = () => { patch(st.id, s => { const x = s.boreholes.find(y => y.id === b.id)!; x.head = { ...x.head, ...head } as any }); useStore.getState().toast({ title: 'حُفظت بيانات الحفرة كمسودة', tone: 'ok' }) }
  const addLayer = () => {
    patch(st.id, s => {
      const x = s.boreholes.find(y => y.id === b.id)!; const idx = x.layers.length + 1; const layerId = `L-${bhNo}${idx}`
      x.layers.push({ id: layerId, from: L.from!, to: L.to!, uscs: L.uscs as USCS, gradation: L.gradation, color: L.color, moisture: L.moisture, description: `${USCS_LIST.find(u => u.v === L.uscs)?.l.split('— ')[1]}، ${L.color}، ${L.moisture}`, spt: L.uscs === 'ROCK' ? undefined : L.spt, n: L.uscs === 'ROCK' ? undefined : n, rec: L.rec, offsite: offsite ? { reason: offReason } : undefined, photo: L.photo })
      samples.forEach((sm, i) => { const kind = L.uscs === 'ROCK' ? 'rock' : 'soil'; const sid = `${kind === 'rock' ? 'C' : 'S'}-${bhNo}${idx}${samples.length > 1 ? String.fromCharCode(97 + i) : ''}`
        x.samples.push({ id: sid, layerId, type: sm.type, kind, from: +((L.from! + L.to!) / 2 - 0.2).toFixed(2), to: +((L.from! + L.to!) / 2 + 0.25).toFixed(2), fieldUSCS: L.uscs as USCS, labStatus: 'ready', tests: kind === 'rock' ? [{ id: uid('t'), name: 'الضغط غير المحصور (UCS)', method: 'ASTM D7012', mandatory: true, unit: 'MPa' }] : [{ id: uid('t'), name: 'التحليل الحبيبي', method: 'ASTM D422', mandatory: true }, { id: uid('t'), name: 'حدود أتربرج', method: 'ASTM D4318', mandatory: true }, { id: uid('t'), name: 'معامل الرطوبة', method: 'ASTM D2216', mandatory: true, unit: '%' }] }) })
      if (L.photo) x.photos.push(L.photo)
      x.executedDepth = L.to!
    })
    setL({ from: L.to, uscs: 'SM', gradation: 'ناعم إلى متوسط', color: 'بني فاتح', moisture: 'رطبة قليلاً' }); setSamples([{ type: 'SPT' }]); setOffsite(false); setOffReason('')
  }
  const finish = () => { patch(st.id, s => { const x = s.boreholes.find(y => y.id === b.id)!; x.status = 'done'; x.head = { ...x.head, date: x.head?.date ?? new Date().toISOString() } as any; if (notReached) (x as any).notReachedReason = notReached }); setComplete(false); nav(`/requests/${r.id}/study/borehole/${b.id}/log`) }

  return (
    <>
      <PageHeader crumbs={[{ label: r.id, to: `/requests/${r.id}` }, { label: 'الدراسة الجيوتقنية', to: `/requests/${r.id}/study/3` }, { label: b.code }]} title={`جسة ${b.code}`} sub={`${r.project} · ${st.ref} · العمق المعتمد ${b.approvedDepth} م · ${b.moved ? `نُقلت ${b.moved} م عن الموقع المعتمد بمبرر` : 'الموقع مطابق للمعتمد'}`}
        meta={<><Badge tone={BOREHOLE_STATUS[b.status].tone} dot size="xs">{BOREHOLE_STATUS[b.status].ar}</Badge>{b.geoVerified && <Badge tone="ok" size="xs"><MapPin className="size-3" />التحقق الجغرافي: مطابق ({b.geoVerified.distance} م)</Badge>}<span className="ltr meta">{(b.actual ?? b.operational ?? b.approved).n.toFixed(5)}, {(b.actual ?? b.operational ?? b.approved).e.toFixed(5)}</span></>}
        actions={<>{b.status !== 'ready' && <ButtonLink variant="secondary" icon={Printer} to={`/requests/${r.id}/study/borehole/${b.id}/log`}>سجل الجسة</ButtonLink>}{b.status === 'in-progress' && isL && <Button variant="secondary" icon={Save} onClick={saveHead}>حفظ كمسودة</Button>}</>} />
      <div className="mb-3 grid grid-cols-2 gap-3 md:grid-cols-5"><Kpi label="العمق المنفَّذ" value={b.executedDepth ?? 0} unit={`/ ${b.approvedDepth} م`} tone="accent" hint={<Progress value={((b.executedDepth ?? 0) / b.approvedDepth) * 100} />} /><Kpi label="الطبقات" value={b.layers.length} /><Kpi label="العينات" value={b.samples.length} hint={`${b.samples.filter(s => s.kind === 'rock').length} صخرية`} /><Kpi label="منسوب المياه" value={b.head?.water24h ?? '—'} unit="م" hint="بعد 24 ساعة" /><Kpi label="المنفّذ الفعلي" value={<span className="text-[14px]">{b.head?.technician ?? user.name}</span>} hint={`${delegate ? `المفوَّض على الطلب: ${delegate} · ` : ''}${fmtDate(b.head?.date)}`} /></div>

      {b.status === 'ready' && isL && <Section title="التحقق من الموقع قبل البدء" icon={MapPin} className="mb-3 border-brand-300 ring-2 ring-brand-100" bodyClass="p-3"><div className="flex flex-wrap items-center justify-between gap-3"><span className="text-[12.5px]">تتحقق المنصة من وجودك ضمن {rules.geofenceMeters} م من الموقع التشغيلي (B.R.183). الموقع الحالي: <b className="text-ok-700">على بعد 1.2 م — مطابق</b>.</span><Button icon={MapPin} onClick={start}>بدء تنفيذ الجسة {b.code}</Button></div></Section>}

      <div className="grid grid-cols-12 gap-3">
        <div className="col-span-12 grid content-start gap-3 xl:col-span-8">
          <Section title="بيانات الحفرة" desc="يتعبأ تلقائياً: المشروع، رقم الجسة، الإحداثيات من GPS، الفني" bodyClass="p-3">
            <div className="grid gap-3 sm:grid-cols-4"><Field label="العمق المعتمد (م)"><Input value={b.approvedDepth} readOnly className="ltr" /></Field><Field label="منسوب سطح الأرض (م)"><Input type="number" step="0.01" value={head.groundLevel ?? ''} onChange={e => setHead({ ...head, groundLevel: +e.target.value })} className="ltr" disabled={readOnly} /></Field><Field label="طريقة الحفر" required><Select value={head.method} onChange={e => setHead({ ...head, method: e.target.value })} disabled={readOnly}><option>حفر دوراني رطب (Rotary Wash)</option><option>حفر دوراني جاف (Dry Rotary)</option><option>حفر لولبي (Auger)</option></Select></Field><Field label="نوع الحفّار"><Input value={head.rig ?? ''} onChange={e => setHead({ ...head, rig: e.target.value })} className="ltr" disabled={readOnly} /></Field><Field label="قطر الحفرة (مم)" required><Input type="number" value={head.diameter} onChange={e => setHead({ ...head, diameter: +e.target.value })} className="ltr" disabled={readOnly} /></Field><Field label="عمق التغليف (م)"><Input type="number" step="0.5" value={head.casing ?? ''} onChange={e => setHead({ ...head, casing: +e.target.value })} className="ltr" disabled={readOnly} /></Field><Field label="المياه — لحظي (م)"><Input type="number" step="0.1" value={head.waterInstant ?? ''} onChange={e => setHead({ ...head, waterInstant: +e.target.value })} className="ltr" disabled={readOnly} /></Field><Field label="المياه — بعد 24 س (م)"><Input type="number" step="0.1" value={head.water24h ?? ''} onChange={e => setHead({ ...head, water24h: +e.target.value })} className="ltr" disabled={readOnly} /></Field></div>
          </Section>
          {b.status === 'in-progress' && isL && (
            <Section title={`طبقة جديدة — من ${L.from} م إلى:`} desc={`الرمز التلقائي L-${bhNo}${b.layers.length + 1}`} actions={<button type="button" onClick={() => setOffsite(o => !o)} className={cx('text-[11.5px] underline', offsite ? 'text-warn-600' : 'text-ink-500')}>{offsite ? 'إدخال خارج الموقع — مفعّل' : 'إدخال يدوي خارج الموقع'}</button>} bodyClass="p-3">
              {offsite && <Field label="سبب عدم مطابقة الموقع الجغرافي" required hint='يظهر في تفاصيل الجسة بعلامة "خارج الموقع" (B.R.183)' className="mb-3"><Textarea value={offReason} onChange={e => setOffReason(e.target.value)} className="min-h-14" /></Field>}
              <div className="grid gap-3 sm:grid-cols-4"><Field label="نهاية الطبقة (م)" required><Input type="number" step="0.5" value={L.to ?? ''} onChange={e => setL({ ...L, to: +e.target.value })} className="ltr" /></Field><Field label="رمز USCS (حقلي)" required><Select value={L.uscs} onChange={e => setL({ ...L, uscs: e.target.value as USCS })}>{USCS_LIST.map(u => <option key={u.v} value={u.v}>{u.l}</option>)}</Select></Field><Field label="التدرج"><Select value={L.gradation} onChange={e => setL({ ...L, gradation: e.target.value })}><option>ناعم</option><option>ناعم إلى متوسط</option><option>متوسط</option><option>متوسط إلى خشن</option><option>خشن</option></Select></Field><Field label="اللون"><Select value={L.color} onChange={e => setL({ ...L, color: e.target.value })}><option>بني فاتح</option><option>بني</option><option>بني داكن</option><option>رمادي فاتح</option><option>رمادي</option></Select></Field><Field label="الرطوبة"><Select value={L.moisture} onChange={e => setL({ ...L, moisture: e.target.value })}><option>جافة</option><option>رطبة قليلاً</option><option>رطبة</option><option>مبللة</option><option>مشبعة</option></Select></Field><Field label="REC % (استرداد)"><Input type="number" value={L.rec ?? ''} onChange={e => setL({ ...L, rec: +e.target.value })} className="ltr" /></Field><Field label="ملاحظات" className="sm:col-span-2"><Input value={L.description ?? ''} onChange={e => setL({ ...L, description: e.target.value })} placeholder="عدسات طمي…" /></Field></div>
              {L.uscs !== 'ROCK' && <div className="mt-3 rounded-sm bg-ink-50 p-3"><div className="mb-2 text-[12.5px] font-bold">دقّات SPT — لكل 15 سم (ASTM D1586 · N = الدقتان الثانية + الثالثة)</div><div className="grid grid-cols-4 items-end gap-3">{[0, 1, 2].map(i => <Field key={i} label={`15 سم ${['الأولى', 'الثانية', 'الثالثة'][i]}`}><Input type="number" value={L.spt?.[i] ?? ''} onChange={e => { const s = [...(L.spt ?? [0, 0, 0])] as [number, number, number]; s[i] = +e.target.value; setL({ ...L, spt: s }) }} className="ltr" /></Field>)}<div className="rounded-sm bg-brand-50 px-3 py-1.5 text-[12.5px] font-bold text-brand-800">{n != null ? `N = ${n} — ${nDesc(n)}` : 'N = —'}{n != null && n <= 8 && <div className="text-[11px] font-medium text-warn-700">مؤشر سبخة — يفرض التحليل الكيميائي الكامل</div>}</div></div></div>}
              <div className="mt-3 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setL({ ...L, photo: `layer-${b.code}-${b.layers.length + 1}.jpg` })} className="flex items-center justify-center gap-2 rounded-sm border border-dashed border-ink-300 bg-ink-25 py-4 text-[12.5px] text-ink-600 hover:border-brand-500"><Camera className="size-4" />{L.photo ? `✓ ${L.photo} — مع الوقت والإحداثيات` : 'إضافة صورة للطبقة (تُسجَّل مع الوقت والإحداثيات)'}</button><div className="rounded-sm border border-ink-200 p-2.5"><div className="mb-1.5 text-[12.5px] font-bold">العينات من هذه الطبقة</div>{samples.map((sm, i) => <div key={i} className="mb-1.5 flex items-center gap-2"><Code>{L.uscs === 'ROCK' ? 'C' : 'S'}-{bhNo}{b.layers.length + 1}{samples.length > 1 ? String.fromCharCode(97 + i) : ''}</Code><Select value={sm.type} onChange={e => setSamples(samples.map((x, j) => j === i ? { type: e.target.value as any } : x))} className="h-8 flex-1 text-[12px]"><option value="SPT">SPT — اختراق قياسي</option><option value="UD">UD — غير مقلقلة</option><option value="D">D — مقلقلة</option><option value="CS">CS — كور صخري</option></Select></div>)}<button type="button" onClick={() => setSamples([...samples, { type: 'SPT' }])} className="text-[11.5px] font-semibold text-brand-700 hover:underline">+ عينة أخرى من نفس الطبقة</button></div></div>
              <div className="mt-3 flex justify-end"><Button icon={Plus} disabled={!canAdd} onClick={addLayer}>إضافة الطبقة</Button></div>
            </Section>
          )}
          <Section title={`الطبقات المسجّلة (${b.layers.length})`} bodyClass="p-3">{b.layers.length === 0 ? <div className="py-4 text-center text-[12.5px] text-ink-500">لم تُسجَّل طبقات بعد — ابدأ من سطح الأرض (0 م).</div> : <ul className="grid gap-1">{b.layers.map(l => <li key={l.id} className="flex items-center gap-3 rounded-sm border border-ink-100 px-3 py-2 text-[12.5px]" style={{ borderInlineStartWidth: 4, borderInlineStartColor: USCS_COLOR[l.uscs] }}><span className="num w-16 text-[11.5px] text-ink-500">{l.from}–{l.to} م</span><Code>{l.uscs}</Code><span className="font-semibold">{l.id}</span><span className="truncate text-ink-600">{l.description}{l.n != null && ` — N=${l.n}`}{l.rec != null && ` — REC ${l.rec}%`}</span><span className="ms-auto meta">{b.samples.filter(s => s.layerId === l.id).map(s => s.id).join('، ')}</span>{l.offsite && <Badge tone="warn" size="xs"><AlertTriangle className="size-3" />خارج الموقع</Badge>}</li>)}</ul>}</Section>
        </div>
        <div className="col-span-12 grid content-start gap-3 xl:col-span-4">
          <Section title="العمود الجيولوجي" bodyClass="p-3"><div className="flex gap-3"><div className="relative h-64 w-16 overflow-hidden rounded-sm border border-ink-200 bg-ink-50">{b.layers.map(l => <div key={l.id} title={`${l.id} ${l.uscs}`} className="absolute inset-x-0 grid place-items-center border-b border-ink-0 text-[9px] font-bold text-ink-800" style={{ top: `${(l.from / b.approvedDepth) * 100}%`, height: `${((l.to - l.from) / b.approvedDepth) * 100}%`, background: USCS_COLOR[l.uscs], backgroundImage: 'radial-gradient(rgba(0,0,0,.15) 1px, transparent 1px)', backgroundSize: '5px 5px' }}>{l.uscs}</div>)}{b.head?.water24h != null && <div className="absolute inset-x-0 border-t-2 border-dashed border-info-500" style={{ top: `${(b.head.water24h / b.approvedDepth) * 100}%` }} />}</div><ul className="grid flex-1 content-start gap-1 text-[11.5px]">{b.layers.map(l => <li key={l.id} className="flex items-center gap-1.5"><i className="size-2.5 rounded-xs border border-ink-300" style={{ background: USCS_COLOR[l.uscs] }} /><span className="num w-14 text-ink-500">{l.from}–{l.to}</span><b>{l.uscs}</b><span className="meta">N={l.n ?? '—'}</span></li>)}{b.head?.water24h != null && <li className="flex items-center gap-1.5 text-info-700"><i className="h-0 w-2.5 border-t-2 border-dashed border-info-500" />منسوب المياه {b.head.water24h} م</li>}</ul></div></Section>
          <Section title="الموقع والتحقق الجغرافي" bodyClass="p-2">{(() => { const c = b.actual ?? b.operational ?? b.approved; return <GeoMap center={[c.n, c.e]} zoom={18} pins={[{ lat: b.approved.n, lng: b.approved.e, label: `${b.code} معتمد`, tone: 'neutral' }, { lat: c.n, lng: c.e, label: `${b.code} تشغيلي`, tone: 'brand' }]} geofenceM={useStore.getState().rules.geofenceMeters} height={180} /> })()}<p className="meta mt-1.5 px-1">الدائرة = النطاق المسموح ({useStore.getState().rules.geofenceMeters} م) · المسافة المسجلة {b.geoVerified?.distance ?? '—'} م · GPS الجهاز ±3 م</p></Section>
          {(() => { const ph = photosFor({ requestId: r.id, boreholeCode: b.code }); return <Section title={`صور الجسة (${ph.length})`} bodyClass="p-3"><PhotoGrid photos={ph} cols={3} size="sm" /></Section> })()}
          {b.status === 'in-progress' && isL && <div className="grid gap-2"><Button icon={CheckCircle2} disabled={b.layers.length === 0} onClick={() => setComplete(true)}>{reached ? 'بلغت العمق المعتمد — إكمال الجسة وتوليد السجل' : 'إكمال الجسة (لم يُبلغ العمق المعتمد)'}</Button><Button variant="secondary" onClick={() => nav(`/requests/${r.id}/study/3`)}>رجوع لخريطة الجسات</Button></div>}
          {b.status === 'done' && <ButtonLink variant="secondary" to={`/requests/${r.id}/study/3`}>رجوع لخريطة الجسات</ButtonLink>}
        </div>
      </div>
      <Modal open={complete} onClose={() => setComplete(false)} title="إكمال الجسة وتوليد سجل الجسة" width="sm" footer={<><Button variant="secondary" onClick={() => setComplete(false)}>تراجع</Button><Button disabled={!reached && notReached.trim().length < 10} onClick={finish}>إكمال وتوليد Borehole Log</Button></>}>{reached ? <p className="text-[13px]">بلغت الجسة العمق المعتمد ({b.approvedDepth} م) بـ {b.layers.length} طبقات و{b.samples.length} عينات. سيُولَّد سجل الجسة تلقائياً ويُحدَّث لاحقاً بالنتائج المعملية (B.R.189).</p> : <><Callout tone="warn" compact className="mb-2">العمق المنفَّذ {b.executedDepth} م أقل من المعتمد {b.approvedDepth} م — يجب توثيق السبب (B.R.191).</Callout><Field label="سبب عدم الوصول للعمق المعتمد" required><Textarea value={notReached} onChange={e => setNotReached(e.target.value)} placeholder="مثال: رفض الحفر عند 12 م — صخر صلب" /></Field></>}</Modal>
    </>
  )
}

/* ───────── Borehole Log — generated (B.R.189) ───────── */
export function BoreholeLog() {
  const { id, bhId } = useParams()
  const r = useStore(s => s.requests.find(x => x.id === id))!
  const st = useStore(s => s.studies.find(x => x.requestId === id))!
  const b = st.boreholes.find(x => x.id === bhId)!
  const gl = b.head?.groundLevel ?? 0
  const labFor = (layerId: string) => b.samples.filter(s => s.layerId === layerId).map(s => s.labUSCS).filter(Boolean)[0]
  return (
    <>
      <PageHeader crumbs={[{ label: r.id, to: `/requests/${r.id}` }, { label: 'الدراسة الجيوتقنية', to: `/requests/${r.id}/study/3` }, { label: b.code, to: `/requests/${r.id}/study/borehole/${b.id}` }, { label: 'سجل الجسة' }]} title={`سجل الجسة — ${b.code}`} sub="BOREHOLE LOG — مولَّد تلقائياً من بيانات الجسة والطبقات والعينات والاختبارات الحقلية · يُحدَّث بالنتائج المعملية المعتمدة" actions={<><Button variant="secondary" icon={Printer}>طباعة</Button><Button variant="secondary" icon={Download}>تنزيل PDF</Button></>} />
      <div className="card overflow-hidden">
        <div className="flex flex-wrap items-center justify-between gap-3 bg-brand-800 px-4 py-3 text-white"><div><div className="text-lg font-bold text-lime-300">{b.code}</div><div className="text-[11px] text-white/70">{st.ref} · {r.project} · قطعة {st.prelim.parcel} مخطط {st.prelim.plan}</div></div><div className="text-end"><div className="font-bold">BOREHOLE LOG — سجل الجسة</div><div className="text-[11px] text-white/70">{b.status === 'done' ? `تم التوليد تلقائياً · ${fmtDate(b.head?.date)}` : 'مسودة — الجسة قيد التنفيذ'}</div></div></div>
        <div className="grid grid-cols-2 gap-3 border-b border-ink-200 px-4 py-3 sm:grid-cols-4 lg:grid-cols-8">{[['طريقة الحفر', b.head?.method], ['الحفّار', b.head?.rig ?? '—'], ['قطر الحفرة', `${b.head?.diameter} مم`], ['منسوب الأرض', `+${gl} م`], ['العمق الكلي', `${b.executedDepth ?? 0} م`], ['التغليف', `${b.head?.casing ?? '—'} م`], ['المياه (لحظي)', b.head?.waterInstant != null ? `${b.head.waterInstant} م ▽` : '—'], ['المياه (24 س)', b.head?.water24h != null ? `${b.head.water24h} م ▼` : '—']].map(([k, v]) => <div key={k}><div className="data-label">{k}</div><div className="num text-[12.5px] font-semibold">{v}</div></div>)}</div>
        <Table className="rounded-none border-0"><thead><tr><Th>العمق</Th><Th>المنسوب</Th><Th>العمود</Th><Th>الطبقة</Th><Th>USCS حقلي</Th><Th>USCS معملي</Th><Th>الوصف</Th><Th>العينة</Th><Th>SPT</Th><Th>N</Th><Th>REC%</Th></tr></thead><tbody>{b.layers.map(l => <tr key={l.id}><Td className="num"><b>{l.from.toFixed(1)}</b><div className="meta">-{l.to.toFixed(1)}</div></Td><Td className="num text-[11.5px]"><div className="text-info-600">{(gl - l.from).toFixed(2)}</div><div className="text-ink-500">{(gl - l.to).toFixed(2)}</div></Td><Td><div className="h-9 w-9 rounded-xs border border-ink-200" style={{ background: USCS_COLOR[l.uscs], backgroundImage: 'radial-gradient(rgba(0,0,0,.18) 1px, transparent 1px)', backgroundSize: '5px 5px' }} /></Td><Td className="font-bold text-brand-700">{l.id}</Td><Td><Code>{l.uscs}</Code></Td><Td>{labFor(l.id) ? <Code>{labFor(l.id)}</Code> : <span className="meta">بانتظار المعمل</span>}</Td><Td className="text-[12px]">{l.description}{l.offsite && <Badge tone="warn" size="xs" className="ms-1">خارج الموقع</Badge>}</Td><Td className="text-[12px] font-semibold">{b.samples.filter(s => s.layerId === l.id).map(s => s.id).join('، ') || '—'}</Td><Td className="ltr num text-[12px]">{l.spt ? l.spt.join('-') : '—'}</Td><Td className="num font-bold text-brand-700">{l.n ?? '—'}</Td><Td className="num">{l.rec ?? '—'}</Td></tr>)}</tbody></Table>
        <div className="flex flex-wrap gap-5 border-t border-ink-200 px-4 py-2.5 text-[12.5px]"><span>الطبقات <b className="num">{b.layers.length}</b></span><span>العينات <b className="num">{b.samples.length}</b></span><span>العمق النهائي <b className="num">-{(b.executedDepth ?? 0).toFixed(1)} م</b></span><span>الفني <b>{b.head?.technician}</b></span><span>الإحداثيات <b className="ltr num">{(b.actual ?? b.approved).n.toFixed(5)}, {(b.actual ?? b.approved).e.toFixed(5)}</b></span>{(b as any).notReachedReason && <span className="text-warn-700">لم يُبلغ العمق المعتمد: {(b as any).notReachedReason}</span>}<span className="ms-auto meta">SBC 303 §2.6 (6) — سجل الجسة مع SPT وREC</span></div>
      </div>
      <div className="mt-3 grid gap-3 lg:grid-cols-3">
        <Section title="منحنى SPT-N مع العمق" desc="ASTM D1586" bodyClass="p-3">
          {(() => { const D = Math.max(b.executedDepth ?? 0, b.approvedDepth, 1); const W = 260, H = 200, px = 34, py = 10; const pts = b.layers.filter(l => l.n != null).map(l => ({ d: (l.from + l.to) / 2, n: l.n! })); const x = (n: number) => px + (Math.min(n, 60) / 60) * (W - px - 8); const y = (d: number) => py + (d / D) * (H - py - 18); return (
            <svg viewBox={`0 0 ${W} ${H}`} className="w-full" style={{ direction: 'ltr' }}>
              {[0, 15, 30, 45, 60].map(n => <g key={n}><line x1={x(n)} x2={x(n)} y1={py} y2={H - 18} stroke="#E5E7EB" strokeDasharray="3 3" /><text x={x(n)} y={H - 5} fontSize="9" fill="#6C727E" textAnchor="middle">{n}</text></g>)}
              {Array.from({ length: Math.floor(D / 3) + 1 }, (_, i) => i * 3).map(d => <g key={d}><line x1={px} x2={W - 8} y1={y(d)} y2={y(d)} stroke="#F3F4F6" /><text x={px - 4} y={y(d) + 3} fontSize="9" fill="#6C727E" textAnchor="end">{d} م</text></g>)}
              {b.layers.map(l => <rect key={l.id} x={px} width={W - px - 8} y={y(l.from)} height={Math.max(0, y(l.to) - y(l.from))} fill={USCS_COLOR[l.uscs]} opacity="0.35" />)}
              {b.head?.water24h != null && <line x1={px} x2={W - 8} y1={y(b.head.water24h)} y2={y(b.head.water24h)} stroke="#156FEE" strokeDasharray="4 3" />}
              {pts.length > 1 && <polyline points={pts.map(p => `${x(p.n)},${y(p.d)}`).join(' ')} fill="none" stroke="#1E6355" strokeWidth="2" />}
              {pts.map(p => <g key={p.d}><circle cx={x(p.n)} cy={y(p.d)} r="4" fill="#1E6355" stroke="#fff" strokeWidth="1.5" /><text x={x(p.n) + 7} y={y(p.d) + 3} fontSize="9.5" fontWeight="700" fill="#104840">{p.n}</text></g>)}
              <text x={W - 8} y={py + 8} fontSize="9" fill="#6C727E" textAnchor="end">N (ضربة/30 سم)</text>
            </svg>) })()}
          <p className="meta mt-1">الخط الأزرق المتقطع: منسوب المياه بعد 24 س · الطبقة الصخرية بلا SPT (كور CS).</p>
        </Section>
        <Section title="العينات والاختبارات المعملية" bodyClass="p-0">
          <table className="w-full text-[11.5px]"><thead><tr className="bg-ink-50 text-[10.5px] text-ink-500"><th className="px-3 py-1.5 text-start font-semibold">العينة</th><th className="px-2 py-1.5 text-start font-semibold">العمق</th><th className="px-2 py-1.5 text-start font-semibold">النوع</th><th className="px-2 py-1.5 text-start font-semibold">الاختبارات</th><th className="px-3 py-1.5 text-start font-semibold">الحالة</th></tr></thead>
            <tbody>{b.samples.map(sm => <tr key={sm.id} className="border-t border-ink-100"><td className="whitespace-nowrap px-3 py-1.5 font-semibold">{sm.id}</td><td className="num whitespace-nowrap px-2 py-1.5">{sm.from}–{sm.to} م</td><td className="px-2 py-1.5">{sm.type}</td><td className="px-2 py-1.5">{sm.tests.map(t => t.method).join(' · ')}</td><td className="px-3 py-1.5"><Badge tone={sm.labStatus === 'done' ? 'ok' : 'neutral'} size="xs">{sm.labStatus === 'done' ? 'معتمدة' : 'بانتظار المعمل'}</Badge></td></tr>)}</tbody></table>
        </Section>
        <Section title="مفتاح الرموز — USCS" desc="ASTM D2487" bodyClass="p-3">
          <ul className="grid grid-cols-2 gap-1.5 text-[11.5px]">{Object.entries({ SM: 'رمل طمي', SC: 'رمل طيني', SW: 'رمل حسن التدرج', SP: 'رمل سيئ التدرج', ML: 'طمي منخفض اللدونة', CL: 'طين منخفض اللدونة', CH: 'طين عالي اللدونة', GW: 'حصى حسن التدرج', GP: 'حصى سيئ التدرج', ROCK: 'صخر' }).map(([k, v]) => <li key={k} className="flex items-center gap-2"><span className="size-4 shrink-0 rounded-xs border border-ink-200" style={{ background: USCS_COLOR[k], backgroundImage: 'radial-gradient(rgba(0,0,0,.18) 1px, transparent 1px)', backgroundSize: '4px 4px' }} /><Code>{k}</Code><span className="truncate text-ink-600">{v}</span></li>)}</ul>
          <div className="mt-3 grid grid-cols-2 gap-1.5 text-[11px] text-ink-600"><span>▽ مياه لحظية</span><span>▼ مياه بعد 24 س</span><span>SPT: ضربات كل 15 سم</span><span>N = الدقتان 2 + 3</span></div>
        </Section>
      </div>
      <div className="mt-3 flex justify-between text-[12.5px]"><Link to={`/requests/${r.id}/study/borehole/${b.id}`} className="font-semibold text-brand-700 hover:underline">رجوع لتفاصيل الجسة</Link><Link to={`/requests/${r.id}/study/3`} className="font-semibold text-brand-700 hover:underline">خريطة الجسات</Link></div>
    </>
  )
}
