/* ─────────────────────────────────────────────────────────────────────────────
   Evidence layer — what a real accredited lab (ISO/IEC 17025 §7.4/7.6/7.8) produces
   around every number: photos with capture metadata, calibrated equipment, sample
   chain of custody & archive, specimen dimensions, and the measurement method sheet.
   The photos are placeholders taken from the reference GSSAAT/سماء report in
   References/ — replace with the client's own assets before any public demo.
   ───────────────────────────────────────────────────────────────────────────── */

export type PhotoKind = 'sample' | 'specimen' | 'measurement' | 'equipment' | 'site' | 'instrument'
export interface Photo {
  id: string; file: string; kind: PhotoKind; caption: string
  takenAt: string; lat?: number; lng?: number; accuracyM?: number; device: string
  requestId?: string; testId?: string; sampleId?: string; boreholeCode?: string; hash: string
}
export interface Equipment {
  id: string; labId: string; name: string; type: string; serial: string; range: string; resolution: string
  calibratedAt: string; calibrationDue: string; certificate: string; provider: string; status: 'صالح' | 'قارب الانتهاء' | 'منتهٍ' | 'خارج الخدمة'; location: string
}
export interface CustodyEvent { at: string; step: 'جمع' | 'نقل' | 'استلام' | 'تجهيز' | 'اختبار' | 'تخزين' | 'إتلاف'; by: string; where: string; note?: string; tempC?: number }
export interface ArchivedSample {
  id: string; requestId: string; testId?: string; boreholeCode?: string; labId: string
  kind: 'كور خرساني' | 'مكعب خرساني' | 'تربة مضطربة' | 'تربة غير مضطربة (UD)' | 'عينة SPT' | 'كور صخري' | 'إسفلت' | 'ركام' | 'حديد تسليح'
  designation: string; collectedAt: string; lat: number; lng: number; collectedBy: string
  dims: Record<string, string>; massG?: number; condition: 'سليمة' | 'متشققة' | 'مكسورة جزئياً'
  status: 'في الموقع' | 'قيد النقل' | 'مستلمة' | 'قيد التجهيز' | 'قيد الاختبار' | 'مختبرة' | 'مؤرشفة' | 'متلفة'
  storage: string; retentionUntil: string; sealNo: string; photos: string[]; custody: CustodyEvent[]
}
export interface MethodSheet {
  refTestId: string; standard: string; title: string; procedure: string[]; specimen: string; specimenFields: { key: string; label: string; unit: string }[]
  equipment: string[]; environment: string; uncertainty: string; reporting: string; acceptance: string; form: string
}

const day = (d: number, h = 9) => new Date(Date.now() - d * 864e5 + (h - 9) * 36e5).toISOString()
const H = (s: string) => `sha256:${Array.from(s).reduce((a, c) => (a * 31 + c.charCodeAt(0)) >>> 0, 7).toString(16).padStart(8, '0')}…`
const P = (id: string, file: string, kind: PhotoKind, caption: string, d: number, extra: Partial<Photo> = {}): Photo => ({ id, file: `/evidence/${file}.jpg`, kind, caption, takenAt: day(d, 10), lat: (extra.requestId === 'TST-2026-044' ? 24.6970 : extra.requestId === 'TST-2026-046' || extra.requestId === 'TST-2026-038' ? 24.8232 : 24.8390) + (d % 7) * 0.0002, lng: (extra.requestId === 'TST-2026-044' ? 46.7590 : extra.requestId === 'TST-2026-046' || extra.requestId === 'TST-2026-038' ? 46.6395 : 46.6540) + (d % 5) * 0.0002, accuracyM: 3 + (d % 4), device: d % 2 ? 'Samsung Galaxy S24 · تطبيق معيار الميداني' : 'iPhone 15 Pro · تطبيق معيار الميداني', hash: H(id + file), ...extra })

export const PHOTOS: Photo[] = [
  // TST-2026-047 — standard tests (proctor / CBR / FDT) on the ring road project
  P('ph-047-1', 'site-grid', 'site', 'تحديد نقاط أخذ العينات ووسمها على الموقع — الطريق الدائري الشمالي', 5, { requestId: 'TST-2026-047', testId: 't1', sampleId: 'SMP-2026-0146' }),
  P('ph-047-2', 'caliper-2', 'measurement', 'قياس قطر العينة بالفرنية الرقمية قبل الاختبار (0.01 مم)', 4, { requestId: 'TST-2026-047', testId: 't1', sampleId: 'SMP-2026-0146' }),
  P('ph-047-3', 'caliper-6', 'measurement', 'قراءة الفرنية: 99.84 مم — القطر الفعلي للعينة', 4, { requestId: 'TST-2026-047', testId: 't1', sampleId: 'SMP-2026-0146' }),
  P('ph-047-4', 'core-level-1', 'specimen', 'التحقق من استواء سطحي العينة قبل التحميل', 3, { requestId: 'TST-2026-047', testId: 't2', sampleId: 'SMP-2026-0147' }),
  P('ph-047-5', 'site-coring', 'site', 'تنفيذ أخذ العينة في الموقع — عمق 1.5 م', 5, { requestId: 'TST-2026-047', testId: 't2', sampleId: 'SMP-2026-0147' }),
  P('ph-047-6', 'site-core-hole', 'site', 'موضع أخذ العينة بعد الاستخراج', 5, { requestId: 'TST-2026-047', testId: 't2b', sampleId: 'SMP-2026-0149' }),
  P('ph-047-7', 'caliper-4', 'measurement', 'قياس سمك الطبقة المدموكة', 3, { requestId: 'TST-2026-047', testId: 't2b', sampleId: 'SMP-2026-0149' }),
  // TST-2026-044 — concrete cores & cubes (completed request on the housing project)
  P('ph-044-1', 'core-before-cut-1', 'sample', 'العينات (كور خرساني) قبل القص — موسومة برقم العينة', 20, { requestId: 'TST-2026-044', sampleId: 'SMP-2026-0131' }),
  P('ph-044-2', 'core-after-cut-1', 'sample', 'العينات بعد القص والتسوية — جاهزة للاختبار', 19, { requestId: 'TST-2026-044', sampleId: 'SMP-2026-0131' }),
  P('ph-044-3', 'core-level-2', 'specimen', 'Co-2 — التحقق من التعامد والاستواء (ASTM C42)', 19, { requestId: 'TST-2026-044', sampleId: 'SMP-2026-0131' }),
  P('ph-044-4', 'core-level-3', 'specimen', 'Co-5 — التحقق من التعامد والاستواء', 19, { requestId: 'TST-2026-044', sampleId: 'SMP-2026-0132' }),
  P('ph-044-5', 'cores-labeled-1', 'sample', 'مجموعة العينات Co-1…Co-7 قبل الإرسال للأرشيف', 18, { requestId: 'TST-2026-044', sampleId: 'SMP-2026-0132' }),
  P('ph-044-6', 'utm-1', 'equipment', 'ماكينة الاختبار الشامل UTM-1000 أثناء التحميل', 18, { requestId: 'TST-2026-044', sampleId: 'SMP-2026-0131' }),
  P('ph-044-7', 'utm-3', 'equipment', 'لحظة الانهيار — نمط الكسر Type 2', 18, { requestId: 'TST-2026-044', sampleId: 'SMP-2026-0131' }),
  P('ph-044-8', 'caliper-7', 'measurement', 'قياس قطر حديد التسليح المستخرج 15.91 مم', 21, { requestId: 'TST-2026-044', sampleId: 'SMP-2026-0135' }),
  P('ph-044-9', 'rebar-samples', 'sample', 'عينات حديد التسليح المستخرجة قبل اختبار الشد', 21, { requestId: 'TST-2026-044', sampleId: 'SMP-2026-0135' }),
  // TST-2026-046 / 038 — geotechnical boreholes
  P('ph-046-1', 'site-coring', 'site', 'BH-01 — الحفار CME-75 في الموقع التشغيلي', 8, { requestId: 'TST-2026-046', boreholeCode: 'BH-01' }),
  P('ph-046-2', 'cores-labeled-2', 'sample', 'BH-01 — عينات SPT مرتبة حسب العمق (S-1…S-3)', 7, { requestId: 'TST-2026-046', boreholeCode: 'BH-01', sampleId: 'S-1' }),
  P('ph-046-3', 'cores-labeled-3', 'sample', 'BH-01 — كور صخري C-1 عمق 12.0–12.5 م', 6, { requestId: 'TST-2026-046', boreholeCode: 'BH-01', sampleId: 'C-1' }),
  P('ph-046-4', 'site-core-hole', 'site', 'BH-02 — فوهة الجسة بعد التغليف 3 م', 2, { requestId: 'TST-2026-046', boreholeCode: 'BH-02' }),
  P('ph-038-1', 'core-level-4', 'specimen', 'C-11 — كور صخري قبل اختبار UCS', 44, { requestId: 'TST-2026-038', boreholeCode: 'BH-01', sampleId: 'C-11' }),
  P('ph-038-2', 'utm-2', 'equipment', 'اختبار الضغط غير المحصور على C-11', 43, { requestId: 'TST-2026-038', boreholeCode: 'BH-01', sampleId: 'C-11' }),
  // Instruments
  P('ph-eq-1', 'halfcell-device', 'instrument', 'جهاز Half-Cell — Proceq Profometer Corrosion', 30),
  P('ph-eq-2', 'halfcell-readings', 'instrument', 'خريطة جهد الصدأ المسجلة من الجهاز (mV vs Cu/CuSO₄)', 30, { requestId: 'TST-2026-044' }),
  P('ph-eq-3', 'caliper-1', 'measurement', 'الفرنية الرقمية Mitutoyo — دقة 0.01 مم', 12),
]

export const EQUIPMENT: Equipment[] = [
  { id: 'EQ-L1-001', labId: 'o-lab1', name: 'ماكينة اختبار شامل UTM-1000', type: 'ضغط/شد', serial: 'UTM-2019-0442', range: '0–1000 kN', resolution: '0.1 kN', calibratedAt: '2026-03-02', calibrationDue: '2027-03-02', certificate: 'CAL-26-0442', provider: 'المركز الوطني للقياس والمعايرة', status: 'صالح', location: 'قاعة الخرسانة' },
  { id: 'EQ-L1-002', labId: 'o-lab1', name: 'فرنية رقمية Mitutoyo 500-196', type: 'أبعاد', serial: 'MT-500-8813', range: '0–150 mm', resolution: '0.01 mm', calibratedAt: '2026-01-15', calibrationDue: '2027-01-15', certificate: 'CAL-26-0118', provider: 'SASO Lab', status: 'صالح', location: 'الميداني — حقيبة 3' },
  { id: 'EQ-L1-003', labId: 'o-lab1', name: 'ميزان إلكتروني 30 kg', type: 'كتلة', serial: 'OH-30K-2201', range: '0–30 kg', resolution: '0.1 g', calibratedAt: '2025-11-20', calibrationDue: '2026-11-20', certificate: 'CAL-25-1902', provider: 'المركز الوطني للقياس والمعايرة', status: 'قارب الانتهاء', location: 'قاعة التربة' },
  { id: 'EQ-L1-004', labId: 'o-lab1', name: 'فرن تجفيف 110°C', type: 'حرارة', serial: 'MM-UF110-77', range: '30–250 °C', resolution: '0.1 °C', calibratedAt: '2026-05-10', calibrationDue: '2027-05-10', certificate: 'CAL-26-0771', provider: 'SASO Lab', status: 'صالح', location: 'قاعة التربة' },
  { id: 'EQ-L1-005', labId: 'o-lab1', name: 'جهاز CBR أوتوماتيكي', type: 'اختراق', serial: 'CBR-A-3310', range: '0–50 kN', resolution: '0.01 kN', calibratedAt: '2026-02-08', calibrationDue: '2027-02-08', certificate: 'CAL-26-0231', provider: 'المركز الوطني للقياس والمعايرة', status: 'صالح', location: 'قاعة التربة' },
  { id: 'EQ-L1-006', labId: 'o-lab1', name: 'جهاز الكثافة الحقلية (مخروط رملي)', type: 'كثافة', serial: 'SC-165-09', range: '—', resolution: '1 g', calibratedAt: '2026-04-01', calibrationDue: '2026-10-01', certificate: 'CAL-26-0402', provider: 'داخلي (رمل معاير)', status: 'قارب الانتهاء', location: 'الميداني — حقيبة 1' },
  { id: 'EQ-L1-007', labId: 'o-lab1', name: 'حفار دوراني CME-75', type: 'حفر', serial: 'CME75-2016-118', range: 'حتى 60 م', resolution: '—', calibratedAt: '2026-06-01', calibrationDue: '2026-12-01', certificate: 'INS-26-0601', provider: 'صيانة دورية معتمدة', status: 'صالح', location: 'الميداني' },
  { id: 'EQ-L1-008', labId: 'o-lab1', name: 'مطرقة SPT أوتوماتيكية 63.5 kg', type: 'اختراق قياسي', serial: 'SPT-AH-2201', range: '—', resolution: '—', calibratedAt: '2026-03-15', calibrationDue: '2027-03-15', certificate: 'CAL-26-0330 (كفاءة الطاقة 78%)', provider: 'GeoCal', status: 'صالح', location: 'الميداني' },
  { id: 'EQ-L1-009', labId: 'o-lab1', name: 'مقياس منسوب المياه (Dipmeter) 50 م', type: 'منسوب', serial: 'DM-50-0093', range: '0–50 m', resolution: '1 cm', calibratedAt: '2026-01-05', calibrationDue: '2027-01-05', certificate: 'CAL-26-0016', provider: 'SASO Lab', status: 'صالح', location: 'الميداني' },
  { id: 'EQ-L1-010', labId: 'o-lab1', name: 'جهاز GPS ميداني Garmin GPSMAP 67', type: 'موقع', serial: 'GM-67-55021', range: '—', resolution: '±3 m', calibratedAt: '2026-01-05', calibrationDue: '2027-01-05', certificate: 'VER-26-0017', provider: 'تحقق داخلي', status: 'صالح', location: 'الميداني' },
  { id: 'EQ-L1-011', labId: 'o-lab1', name: 'مجموعة مناخل ASTM E11', type: 'تدرج', serial: 'SV-E11-2020', range: '0.075–75 mm', resolution: '—', calibratedAt: '2025-09-01', calibrationDue: '2026-09-01', certificate: 'CAL-25-1401', provider: 'SASO Lab', status: 'منتهٍ', location: 'قاعة التربة' },
  { id: 'EQ-L1-012', labId: 'o-lab1', name: 'جهاز Half-Cell Proceq', type: 'جهد صدأ', serial: 'PQ-HC-7781', range: '±1000 mV', resolution: '1 mV', calibratedAt: '2026-02-20', calibrationDue: '2027-02-20', certificate: 'CAL-26-0244', provider: 'Proceq Service', status: 'صالح', location: 'الميداني — حقيبة 2' },
  { id: 'EQ-L1-013', labId: 'o-lab1', name: 'مقياس حرارة/رطوبة القاعة', type: 'بيئة', serial: 'TH-ENV-04', range: '-10–60 °C', resolution: '0.1 °C', calibratedAt: '2026-05-10', calibrationDue: '2027-05-10', certificate: 'CAL-26-0772', provider: 'SASO Lab', status: 'صالح', location: 'قاعة الخرسانة' },
]

const custody = (collected: number, by: string, where: string, extra: CustodyEvent[] = []): CustodyEvent[] => [
  { at: day(collected, 9), step: 'جمع', by, where, note: 'وسم العينة وختم الكيس/الأسطوانة', tempC: 34 },
  { at: day(collected, 13), step: 'نقل', by: 'سائق المختبر — عبدالله فهد', where: 'سيارة مبردة L1-VAN-2', tempC: 22 },
  { at: day(collected, 16), step: 'استلام', by: 'موظف الاستلام — سلطان الحربي', where: 'غرفة الاستلام — المختبر الرئيسي', note: 'الختم سليم · الكتلة مطابقة', tempC: 23 },
  ...extra,
]
export const SAMPLES: ArchivedSample[] = [
  { id: 'SMP-2026-0146', requestId: 'TST-2026-047', testId: 't1', labId: 'o-lab1', kind: 'تربة مضطربة', designation: 'D-1 · تربة طمي رملية', collectedAt: day(4, 9), lat: 24.8390, lng: 46.6540, collectedBy: 'فيصل القحطاني', dims: { 'الكتلة': '5,420 g', 'عمق الأخذ': '1.5 م', 'حجم الكيس': '10 L' }, massG: 5420, condition: 'سليمة', status: 'مختبرة', storage: 'رف A-3 · صندوق 12', retentionUntil: day(-86), sealNo: 'SEAL-118820', photos: ['ph-047-1', 'ph-047-2', 'ph-047-3'], custody: custody(4, 'فيصل القحطاني', 'الطريق الدائري الشمالي — نقطة 3', [{ at: day(3, 9), step: 'اختبار', by: 'محمد السبيعي', where: 'قاعة التربة', note: 'ASTM D1557' }, { at: day(3, 15), step: 'تخزين', by: 'سلطان الحربي', where: 'رف A-3 · صندوق 12' }]) },
  { id: 'SMP-2026-0147', requestId: 'TST-2026-047', testId: 't2', labId: 'o-lab1', kind: 'تربة مضطربة', designation: 'D-2 · تربة رمل طيني', collectedAt: day(4, 10), lat: 24.8393, lng: 46.6544, collectedBy: 'فيصل القحطاني', dims: { 'الكتلة': '6,110 g', 'عمق الأخذ': '1.5 م', 'حجم الكيس': '10 L' }, massG: 6110, condition: 'سليمة', status: 'قيد الاختبار', storage: 'قاعة التربة — طاولة CBR', retentionUntil: day(-86), sealNo: 'SEAL-118821', photos: ['ph-047-4', 'ph-047-5'], custody: custody(4, 'فيصل القحطاني', 'الطريق الدائري الشمالي — نقطة 4', [{ at: day(2, 9), step: 'تجهيز', by: 'نواف الشمري', where: 'قاعة التربة', note: 'نقع 96 ساعة' }]) },
  { id: 'SMP-2026-0149', requestId: 'TST-2026-047', testId: 't2b', labId: 'o-lab1', kind: 'تربة مضطربة', designation: 'FD-1 · مخروط رملي — سطح الطبقة', collectedAt: day(2, 8), lat: 24.8386, lng: 46.6537, collectedBy: 'فيصل القحطاني', dims: { 'الكتلة الرطبة': '2,310 g', 'حجم الحفرة': '1,262 cm³', 'عمق الأخذ': '0.3 م' }, massG: 2310, condition: 'سليمة', status: 'مختبرة', storage: 'رف A-3 · صندوق 13', retentionUntil: day(-88), sealNo: 'SEAL-118834', photos: ['ph-047-6', 'ph-047-7'], custody: custody(2, 'فيصل القحطاني', 'الطريق الدائري الشمالي — محطة 2+450', [{ at: day(1, 11), step: 'اختبار', by: 'فيصل القحطاني', where: 'الموقع + قاعة التربة', note: 'ASTM D1556' }]) },
  { id: 'SMP-2026-0131', requestId: 'TST-2026-044', labId: 'o-lab1', kind: 'كور خرساني', designation: 'Co-1…Co-4 · أعمدة الدور الأرضي', collectedAt: day(21, 9), lat: 24.6970, lng: 46.7590, collectedBy: 'أحمد عبدالوهاب', dims: { 'القطر': '68.0 mm', 'الطول بعد القص': '110–140 mm', 'L/D': '1.62–2.06', 'العدد': '4' }, massG: 945, condition: 'سليمة', status: 'مؤرشفة', storage: 'أرشيف B-1 · صندوق 41', retentionUntil: day(-160), sealNo: 'SEAL-117702', photos: ['ph-044-1', 'ph-044-2', 'ph-044-3', 'ph-044-6', 'ph-044-7'], custody: custody(21, 'أحمد عبدالوهاب', 'حي الربوة — المبنى القائم', [{ at: day(19, 9), step: 'تجهيز', by: 'سامي عبدالحق', where: 'قاعة الخرسانة', note: 'قص وتسوية السطحين' }, { at: day(18, 10), step: 'اختبار', by: 'أحمد عبدالوهاب', where: 'قاعة الخرسانة — UTM-1000', note: 'ASTM C42 · 24°C' }, { at: day(17, 9), step: 'تخزين', by: 'سلطان الحربي', where: 'أرشيف B-1 · صندوق 41', note: 'احتفاظ 6 أشهر ثم إتلاف' }]) },
  { id: 'SMP-2026-0132', requestId: 'TST-2026-044', labId: 'o-lab1', kind: 'كور خرساني', designation: 'Co-5…Co-7 · بلاطة سقف الدور الأول', collectedAt: day(21, 11), lat: 24.6972, lng: 46.7593, collectedBy: 'أحمد عبدالوهاب', dims: { 'القطر': '68.0 mm', 'الطول بعد القص': '112–136 mm', 'العدد': '3' }, massG: 912, condition: 'متشققة', status: 'مؤرشفة', storage: 'أرشيف B-1 · صندوق 41', retentionUntil: day(-160), sealNo: 'SEAL-117703', photos: ['ph-044-4', 'ph-044-5'], custody: custody(21, 'أحمد عبدالوهاب', 'حي الربوة — المبنى القائم', [{ at: day(18, 10), step: 'اختبار', by: 'أحمد عبدالوهاب', where: 'قاعة الخرسانة — UTM-1000' }, { at: day(17, 9), step: 'تخزين', by: 'سلطان الحربي', where: 'أرشيف B-1 · صندوق 41' }]) },
  { id: 'SMP-2026-0135', requestId: 'TST-2026-044', labId: 'o-lab1', kind: 'حديد تسليح', designation: 'R-1…R-3 · سقف الدور الأول', collectedAt: day(21, 12), lat: 24.6971, lng: 46.7592, collectedBy: 'أحمد عبدالوهاب', dims: { 'القطر الاسمي': '16 mm', 'القطر المقاس': '15.91 mm', 'الطول': '600 mm', 'العدد': '3' }, massG: 2860, condition: 'سليمة', status: 'متلفة', storage: '— (أُتلفت بعد الاختبار التدميري)', retentionUntil: day(0), sealNo: 'SEAL-117709', photos: ['ph-044-8', 'ph-044-9'], custody: custody(21, 'أحمد عبدالوهاب', 'حي الربوة — المبنى القائم', [{ at: day(17, 10), step: 'اختبار', by: 'أحمد عبدالوهاب', where: 'قاعة الحديد — UTM-1000', note: 'اختبار شد ASTM A370' }, { at: day(16, 9), step: 'إتلاف', by: 'سلطان الحربي', where: 'حاوية الخردة المعدنية', note: 'اختبار تدميري — لا احتفاظ' }]) },
  { id: 'S-1', requestId: 'TST-2026-046', boreholeCode: 'BH-01', labId: 'o-lab1', kind: 'عينة SPT', designation: 'BH-01 / L-11 · 2.00–2.45 م', collectedAt: day(7, 9), lat: 24.82281, lng: 46.63981, collectedBy: 'فيصل القحطاني', dims: { 'العمق': '2.00–2.45 م', 'الكتلة': '1,240 g', 'الوعاء': 'كيس محكم 5 L' }, massG: 1240, condition: 'سليمة', status: 'مختبرة', storage: 'رف G-2 · صندوق 7', retentionUntil: day(-83), sealNo: 'SEAL-119001', photos: ['ph-046-1', 'ph-046-2'], custody: custody(7, 'فيصل القحطاني', 'حي الياسمين — BH-01', [{ at: day(5, 9), step: 'اختبار', by: 'نواف الشمري', where: 'قاعة التربة', note: 'D422 · D4318 · D2216' }, { at: day(4, 9), step: 'تخزين', by: 'سلطان الحربي', where: 'رف G-2 · صندوق 7' }]) },
  { id: 'C-1', requestId: 'TST-2026-046', boreholeCode: 'BH-01', labId: 'o-lab1', kind: 'كور صخري', designation: 'BH-01 / L-14 · 12.00–12.50 م', collectedAt: day(6, 11), lat: 24.82281, lng: 46.63981, collectedBy: 'فيصل القحطاني', dims: { 'القطر': '54 mm (NQ)', 'الطول': '500 mm', 'REC': '92%', 'RQD': '68%' }, massG: 2880, condition: 'سليمة', status: 'قيد الاختبار', storage: 'صندوق كور BH-01 · #3', retentionUntil: day(-83), sealNo: 'SEAL-119004', photos: ['ph-046-3'], custody: custody(6, 'فيصل القحطاني', 'حي الياسمين — BH-01', [{ at: day(2, 9), step: 'تجهيز', by: 'نواف الشمري', where: 'قاعة الصخر', note: 'قص إلى L/D = 2' }]) },
  { id: 'C-11', requestId: 'TST-2026-038', boreholeCode: 'BH-01', labId: 'o-lab1', kind: 'كور صخري', designation: 'BH-01 / L-54 · 10.00–10.50 م', collectedAt: day(55, 11), lat: 24.82581, lng: 46.6433, collectedBy: 'فيصل القحطاني', dims: { 'القطر': '54 mm (NQ)', 'الطول': '108 mm', 'L/D': '2.0', 'REC': '92%' }, massG: 640, condition: 'سليمة', status: 'مؤرشفة', storage: 'صندوق كور BH-01 (038) · #1', retentionUntil: day(-128), sealNo: 'SEAL-118112', photos: ['ph-038-1', 'ph-038-2'], custody: custody(55, 'فيصل القحطاني', 'حي الياسمين — المرحلة الأولى BH-01', [{ at: day(43, 9), step: 'اختبار', by: 'نواف الشمري', where: 'قاعة الصخر — UTM-1000', note: 'ASTM D7012 · 1.4 MPa' }, { at: day(42, 9), step: 'تخزين', by: 'سلطان الحربي', where: 'صندوق كور #1' }]) },
]

export const METHODS: MethodSheet[] = [
  { refTestId: 'rt-proctor', standard: 'ASTM D1557', title: 'الدمك المعدّل — علاقة الرطوبة/الكثافة', form: 'MTS-10-004 v1.2', procedure: ['تجهيز 5 عينات فرعية بمحتويات رطوبة متدرجة (±2% حول OMC المتوقع)', 'الدمك في قالب 101.6 مم على 5 طبقات × 25 ضربة بمطرقة 4.54 kg من ارتفاع 457 مم', 'وزن القالب + التربة، ثم أخذ عينة رطوبة من الوسط وتجفيفها 110°C حتى ثبات الكتلة', 'رسم منحنى الكثافة الجافة مقابل الرطوبة واستخراج MDD وOMC'], specimen: 'تربة مارة من منخل 19 مم · ≥ 20 kg', specimenFields: [{ key: 'mouldVol', label: 'حجم القالب', unit: 'cm³' }, { key: 'points', label: 'عدد النقاط', unit: '' }, { key: 'hammer', label: 'كتلة المطرقة', unit: 'kg' }, { key: 'passing', label: 'مار 19 مم', unit: '%' }], equipment: ['EQ-L1-003', 'EQ-L1-004', 'EQ-L1-002'], environment: 'قاعة التربة 23±2°C', uncertainty: 'MDD ±0.02 Mg/m³ · OMC ±0.5%', reporting: 'MDD وOMC ومنحنى الدمك ونسبة المار', acceptance: 'درجة الدمك الحقلية ≥ 95% من MDD للطبقات الحاملة' },
  { refTestId: 'rt-cbr', standard: 'ASTM D1883', title: 'نسبة تحمل كاليفورنيا CBR', form: 'MTS-10-006 v1.1', procedure: ['دمك 3 عينات عند OMC بطاقات مختلفة (10/25/56 ضربة)', 'نقع 96 ساعة تحت حمل إضافي 4.54 kg مع قياس الانتفاخ', 'اختراق بمكبس 49.6 مم بمعدل 1.27 مم/دقيقة وتسجيل الحمل عند 2.54 و5.08 مم', 'CBR = حمل الاختراق / الحمل القياسي × 100 مع التصحيح للمنحنى المقعر'], specimen: 'تربة مدموكة في قالب 152.4 مم · 3 قوالب', specimenFields: [{ key: 'blows', label: 'الضربات/طبقة', unit: '' }, { key: 'surcharge', label: 'الحمل الإضافي', unit: 'kg' }, { key: 'soakH', label: 'مدة النقع', unit: 'ساعة' }, { key: 'load254', label: 'الحمل عند 2.54 مم', unit: 'kN' }], equipment: ['EQ-L1-005', 'EQ-L1-003', 'EQ-L1-002'], environment: 'قاعة التربة 23±2°C', uncertainty: 'CBR ±2 نقطة مئوية', reporting: 'CBR عند 2.54/5.08 مم، الانتفاخ %، منحنى الاختراق', acceptance: '≥ 8% تأسيس · ≥ 30% أساس سفلي · ≥ 80% أساس' },
  { refTestId: 'rt-fdt', standard: 'ASTM D1556', title: 'الكثافة الحقلية — المخروط الرملي', form: 'MTS-10-011 v1.0', procedure: ['تسوية السطح وتثبيت الصفيحة وحفر حفرة 100–150 مم', 'وزن التربة المستخرجة وأخذ عينة رطوبة', 'ملء الحفرة بالرمل المعاير من المخروط ووزن الرمل المستهلك', 'حساب حجم الحفرة والكثافة الرطبة ثم الجافة ونسبة الدمك النسبي مقابل MDD'], specimen: 'حفرة ميدانية ≥ 1,000 cm³', specimenFields: [{ key: 'holeVol', label: 'حجم الحفرة', unit: 'cm³' }, { key: 'wetMass', label: 'الكتلة الرطبة', unit: 'g' }, { key: 'sandDensity', label: 'كثافة الرمل المعاير', unit: 'g/cm³' }, { key: 'mc', label: 'المحتوى الرطوبي', unit: '%' }], equipment: ['EQ-L1-006', 'EQ-L1-003', 'EQ-L1-010'], environment: 'ميداني — يُسجَّل الجو', uncertainty: 'الكثافة الجافة ±0.02 Mg/m³', reporting: 'الكثافة الجافة، نسبة الدمك النسبي، الموقع بإحداثيات', acceptance: '≥ 95% من MDD' },
  { refTestId: 'rt-atterberg', standard: 'ASTM D4318', title: 'حدود أتربرج (LL/PL/PI)', form: 'MTS-10-002 v1.3', procedure: ['تجهيز عينة مارة من منخل 425 µm', 'حد السيولة بجهاز كازاجراندي — 3 نقاط بين 15 و35 ضربة', 'حد اللدونة بلف الخيط حتى قطر 3.2 مم', 'PI = LL − PL'], specimen: '≥ 200 g مار 425 µm', specimenFields: [{ key: 'blows', label: 'الضربات (النقطة الوسطى)', unit: '' }, { key: 'trials', label: 'عدد المحاولات', unit: '' }], equipment: ['EQ-L1-003', 'EQ-L1-004'], environment: 'قاعة التربة 23±2°C', uncertainty: 'LL ±2 · PL ±2', reporting: 'LL، PL، PI، ورمز اللدونة على مخطط كازاجراندي', acceptance: 'PI ≤ 6 لمواد الأساس' },
  { refTestId: 'rt-sieve', standard: 'ASTM D422', title: 'التحليل الحبيبي بالمناخل', form: 'MTS-10-001 v1.3', procedure: ['غسل العينة على منخل 75 µm وتجفيفها', 'نخل ميكانيكي 10 دقائق على مجموعة ASTM E11', 'وزن المتبقي على كل منخل وحساب المار التراكمي', 'رسم منحنى التدرج وحساب D10/D30/D60 وCu/Cc'], specimen: '500–2,000 g حسب أكبر حجم حبيبي', specimenFields: [{ key: 'dryMass', label: 'الكتلة الجافة', unit: 'g' }, { key: 'd60', label: 'D60', unit: 'mm' }, { key: 'cu', label: 'Cu', unit: '' }], equipment: ['EQ-L1-011', 'EQ-L1-003', 'EQ-L1-004'], environment: 'قاعة التربة', uncertainty: 'المار ±1%', reporting: 'جدول ومنحنى التدرج، المار من 200', acceptance: 'حسب حدود التدرج للطبقة' },
  { refTestId: 'rt-cube', standard: 'BS EN 12390-3', title: 'مقاومة ضغط المكعبات الخرسانية', form: 'MTS-20-001 v1.4', procedure: ['قياس أبعاد المكعب 150 مم وكتلته', 'تحميل بمعدل 0.6±0.2 MPa/s حتى الانهيار', 'تسجيل حمل الانهيار ونمط الكسر', 'المقاومة = الحمل / المساحة'], specimen: 'مكعب 150×150×150 مم · 3 مكعبات لكل عمر', specimenFields: [{ key: 'dim', label: 'الأبعاد', unit: 'mm' }, { key: 'mass', label: 'الكتلة', unit: 'g' }, { key: 'load', label: 'حمل الانهيار', unit: 'kN' }, { key: 'fracture', label: 'نمط الكسر', unit: '' }], equipment: ['EQ-L1-001', 'EQ-L1-002', 'EQ-L1-013'], environment: 'قاعة الخرسانة 20±2°C · معالجة 20°C', uncertainty: '±1.5 MPa', reporting: 'المقاومة لكل مكعب والمتوسط والكثافة', acceptance: '≥ fcu التصميمية' },
  { refTestId: 'rt-core', standard: 'ASTM C42', title: 'مقاومة ضغط الكور الخرساني', form: 'MTS-20-010 v0.1', procedure: ['قص الكور وتسوية السطحين (Capping) والتحقق من التعامد', 'قياس القطر (متوسط قراءتين) والطول والكتلة', 'التحميل حتى الانهيار وتسجيل نمط الكسر (Type 1–6)', 'تصحيح المقاومة بمعامل L/D وفق الجدول'], specimen: 'كور قطر ≥ 94 مم مفضّل (68 مم مقبول) · L/D 1–2', specimenFields: [{ key: 'dia', label: 'القطر', unit: 'mm' }, { key: 'len', label: 'الطول', unit: 'mm' }, { key: 'mass', label: 'الكتلة', unit: 'g' }, { key: 'ld', label: 'L/D', unit: '' }, { key: 'load', label: 'حمل الانهيار', unit: 'kN' }, { key: 'corr', label: 'معامل التصحيح', unit: '' }, { key: 'fracture', label: 'نمط الكسر', unit: '' }], equipment: ['EQ-L1-001', 'EQ-L1-002', 'EQ-L1-013'], environment: 'قاعة الخرسانة 24°C', uncertainty: '±1.0 MPa', reporting: 'المقاومة الفعلية والمصححة لكل كور والمتوسط', acceptance: '≥ 85% من fc المحددة' },
  { refTestId: 'rt-ucs', standard: 'ASTM D7012', title: 'الضغط غير المحصور للصخر', form: 'MTS-30-003 v1.0', procedure: ['قص الكور إلى L/D = 2 وتسوية السطحين', 'قياس القطر والطول والكتلة', 'التحميل بمعدل ثابت حتى الانهيار', 'UCS = الحمل / المساحة'], specimen: 'كور NQ 54 مم · L/D 2–2.5', specimenFields: [{ key: 'dia', label: 'القطر', unit: 'mm' }, { key: 'len', label: 'الطول', unit: 'mm' }, { key: 'load', label: 'حمل الانهيار', unit: 'kN' }], equipment: ['EQ-L1-001', 'EQ-L1-002'], environment: 'قاعة الصخر 23±2°C', uncertainty: '±3%', reporting: 'UCS ونمط الكسر ورطوبة العينة', acceptance: 'تصنيف الصخر (ISRM)' },
  { refTestId: 'rt-halfcell', standard: 'ASTM C876', title: 'جهد الصدأ Half-Cell', form: 'MTS-20-014 v1.0', procedure: ['تحديد شبكة قياس 20×20 سم على العنصر', 'توصيل القطب بحديد التسليح المكشوف', 'قراءة الجهد عند كل نقطة بقطب Cu/CuSO₄', 'رسم خريطة الجهد وتفسيرها: > −200 mV منخفض · −200…−350 غير مؤكد · < −350 mV مرتفع'], specimen: 'عنصر إنشائي بشبكة قياس', specimenFields: [{ key: 'grid', label: 'الشبكة', unit: 'cm' }, { key: 'points', label: 'عدد النقاط', unit: '' }, { key: 'min', label: 'أدنى جهد', unit: 'mV' }], equipment: ['EQ-L1-012'], environment: 'ميداني — سطح رطب', uncertainty: '±10 mV', reporting: 'خريطة الجهد + احتمالية الصدأ', acceptance: 'حسب ASTM C876 جدول التفسير' },
]

export const photosFor = (f: { requestId?: string; testId?: string; sampleId?: string; boreholeCode?: string; kind?: PhotoKind }) =>
  PHOTOS.filter(p => (!f.requestId || p.requestId === f.requestId) && (!f.testId || p.testId === f.testId) && (!f.sampleId || p.sampleId === f.sampleId) && (!f.boreholeCode || p.boreholeCode === f.boreholeCode) && (!f.kind || p.kind === f.kind))
export const methodFor = (refTestId: string) => METHODS.find(m => m.refTestId === refTestId)
export const SAMPLE_STEPS: ArchivedSample['status'][] = ['في الموقع', 'قيد النقل', 'مستلمة', 'قيد التجهيز', 'قيد الاختبار', 'مختبرة', 'مؤرشفة', 'متلفة']
